### ISSUE TITLE
需要添加GitHub Actions工作流

### ISSUE THREAD

**Issue by langkeyo** [langkeyo/tauri-daily-helper#1]
# GitHub Actions工作流配置

请将以下内容添加到 `.github/workflows/publish.yml` 文件中：

```yaml
name: "Tauri多平台发布"
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
      
      - name: 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: 安装Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: 安装依赖 (Ubuntu)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev
      
      - name: 安装依赖
        run: npm install
      
      - name: 构建应用
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: "日报助手 v__VERSION__"
          args: ${{ matrix.platform == 'macos-latest' && '--target universal-apple-darwin' || '' }}
```

添加此文件后，可以通过以下步骤创建发布：

1. 创建新标签: `git tag v0.1.0`
2. 推送标签: `git push origin v0.1.0`
3. 等待GitHub Actions自动构建所有平台的安装包
